### ISSUE TITLE
Please add BOM

### ISSUE THREAD

**Issue by DarthBanana** [CountDeMonet/Arduino_PKE_Meter#3]
It would be great if you could add the bill of materials (parts list).

**Comment by CountDeMonet** [comment]
Check the gbfans thread. it has all the info https://www.gbfans.com/forum/viewtopic.php?p=4893554#p4893554

**Comment by DarthBanana** [comment]
Thanks for the quick reply!  That is very helpful.


________________________________

**Comment by DarthBanana** [comment]
What about the battery contact plates?

**Comment by CountDeMonet** [comment]
I don't really have a part for that. I think I scavenged something from one of my son's toys.
